server:
  port: ${SERVER_PORT:8080}

spring:
  application:
    name: api-monolito
  config:
<<<<<<< HEAD
    import:  optional:file:.env.prod.properties
=======
    import: optional:file:.env.prod.properties
>>>>>>> 9649de1df1a4341d16ed184b1ccb4d85d31897a0

  data:
    mongodb:
      uri: ${MONGO_URI}
      database: ${MONGO_NAME}
      auto-index-creation: true

  datasource:
    url: ${POSTGRES_URL}
    username: ${POSTGRES_USER}
    password: ${POSTGRES_PASSWORD}
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        jdbc:
          batch_size: 50
        dialect: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true
    generate-ddl: false

  flyway:
    enabled: true
    baseline-on-migrate: true
    locations: classpath:db/migration/test

springdoc:
  api-docs:
    path: /v3/api-docs
    enabled: true
  swagger-ui:
    path: /swagger-ui.html
    enabled: true
    persist-authorization: true

api:
  cors:
    allowed-origins: "${ALLOWED_ORIGIN}"
  security:
    token:
      secret: ${SECRET:secret-00000000000000000000000000000}
